### ISSUE TITLE
Need to show Options of few more Optimized codes in terminal

### ISSUE THREAD

**Issue by PARTHIB-DEB** [ValdonVitija/pyggester#5]
![Screenshot (808)](https://github.com/ValdonVitija/pyggester/assets/103876861/4f2694c5-5c76-41bb-a8cf-e9c3f850b427)

I think , Packadge should give some more options in a table (as Each solution is applicable for each different use-case)

**Comment by ValdonVitija** [comment]
For some usages it is easier to determine what the user should do in terms of using another data structure, but for some other use cases it is necessary to allow a variety of options. In the next release, I will be taking a look at the current implementations, but new suggestions related to data structures part of the built-in collections package, will be added.

**Comment by PARTHIB-DEB** [comment]
Thanks. That feature willl certainly boost the product 👍
